#!/usr/bin/env python3
"""Generate GDPR legal analysis memo DOCX files — English and Korean versions."""

from datetime import date
import os
from pathlib import Path

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Pt, Inches, Cm, RGBColor

DEFAULT_OUTPUT_DIR = Path.home() / "Legal-private" / "gdpr-expert" / "opinions"


def get_output_dir() -> Path:
    raw = os.environ.get("GDPR_EXPERT_PRIVATE_DIR", "").strip()
    output_dir = Path(raw).expanduser() if raw else DEFAULT_OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


OUTPUT_DIR = get_output_dir()


def setup_styles(doc):
    """Configure document styles."""
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x33, 0x33, 0x33)
    pf = style.paragraph_format
    pf.space_after = Pt(6)
    pf.line_spacing = 1.15

    for level, size, bold in [
        ("Heading 1", 18, True),
        ("Heading 2", 14, True),
        ("Heading 3", 12, True),
    ]:
        s = doc.styles[level]
        s.font.name = "Calibri"
        s.font.size = Pt(size)
        s.font.bold = bold
        s.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)
        s.paragraph_format.space_before = Pt(12)
        s.paragraph_format.space_after = Pt(6)

    # Quote style
    if "Quote" not in [s.name for s in doc.styles]:
        quote_style = doc.styles.add_style("Quote", WD_STYLE_TYPE.PARAGRAPH)
    else:
        quote_style = doc.styles["Quote"]
    quote_style.font.name = "Calibri"
    quote_style.font.size = Pt(10)
    quote_style.font.italic = True
    quote_style.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
    quote_style.paragraph_format.left_indent = Cm(1.5)
    quote_style.paragraph_format.space_after = Pt(6)


def add_header_footer(doc, title_text):
    """Add header/footer to the document."""
    section = doc.sections[0]
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)

    header = section.header
    hp = header.paragraphs[0]
    hp.text = title_text
    hp.style.font.size = Pt(8)
    hp.style.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    footer = section.footer
    fp = footer.paragraphs[0]
    fp.text = "CONFIDENTIAL — For internal use only"
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fp.style.font.size = Pt(8)


def add_citation(doc, tag, grade, source, text):
    """Add a formatted citation block."""
    p = doc.add_paragraph()
    run = p.add_run(f"[{tag}] [Grade {grade}] {source}")
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)
    q = doc.add_paragraph(f'"{text}"', style="Quote")
    return q


def generate_english_opinion():
    doc = Document()
    setup_styles(doc)
    add_header_footer(doc, "Legal Analysis Memo — AI Model Training Under GDPR")

    # === TITLE PAGE ===
    for _ in range(4):
        doc.add_paragraph("")

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("LEGAL ANALYSIS MEMO")
    run.bold = True
    run.font.size = Pt(28)
    run.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(
        "Legality of Using Procurement Data for AI Model Training\n"
        "Under the General Data Protection Regulation (EU) 2016/679"
    )
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    doc.add_paragraph("")

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run(f"Date: {date.today().strftime('%d %B %Y')}\n").font.size = Pt(11)
    meta.add_run("Reference: GDPR-2026-LO-001\n").font.size = Pt(11)
    meta.add_run("Classification: CONFIDENTIAL\n").font.size = Pt(11)
    meta.add_run("Generated by: Jinju Legal Orchestrator — Privacy Specialist Kim De Bruyne (김덕배)").font.size = Pt(11)

    doc.add_page_break()

    # === TABLE OF CONTENTS ===
    doc.add_heading("Table of Contents", level=1)
    toc_items = [
        "I.   Executive Summary",
        "II.  Background and Facts",
        "III. Legal Analysis",
        "     A. The Controller/Processor Threshold Issue (Art. 28 GDPR)",
        "     B. Purpose Limitation (Art. 5(1)(b) GDPR)",
        "     C. Legitimate Interest Balancing Test (Art. 6(1)(f) GDPR)",
        "     D. EDPB Position on AI and Personal Data",
        "     E. Digital Omnibus Impact (COM(2025) 837)",
        "IV.  Risk Assessment Summary",
        "V.   Recommendations",
        "VI.  Conclusion",
        "     Disclaimer",
    ]
    for item in toc_items:
        doc.add_paragraph(item)
    doc.add_page_break()

    # === I. EXECUTIVE SUMMARY ===
    doc.add_heading("I. Executive Summary", level=1)

    doc.add_paragraph(
        "Your company operates a B2B SaaS platform that processes procurement data "
        "(invoices, purchase orders, vendor contracts) on behalf of enterprise clients. "
        "You act as a data processor under Article 28 GDPR. Your CTO proposes using this "
        "data to fine-tune a large language model (LLM) for an \"AI-powered spend analytics\" "
        "feature — predicting spending patterns and suggesting cost optimizations."
    )

    doc.add_paragraph(
        "Our analysis concludes that this proposal faces significant legal obstacles under "
        "the current GDPR framework. The primary issue is not the legitimate interest test "
        "itself, but a threshold problem: as a data processor, you cannot unilaterally "
        "determine new purposes for processing client data. Doing so would trigger "
        "Article 28(10) GDPR, re-characterizing your company as a data controller for that "
        "processing — with all attendant obligations and liabilities."
    )

    p = doc.add_paragraph()
    run = p.add_run("Core Finding: ")
    run.bold = True
    p.add_run(
        "Reliance on legitimate interest (Art. 6(1)(f)) is legally problematic because: "
        "(1) a processor cannot invoke a legal basis for processing — only controllers can; "
        "(2) using client data for your own AI training purposes transforms you into a controller "
        "under Art. 28(10), creating significant compliance exposure; and "
        "(3) even if restructured as a controller, purpose limitation and the legitimate interest "
        "balancing test present substantial hurdles given the nature of the data and the "
        "reasonable expectations of data subjects."
    )

    doc.add_page_break()

    # === II. BACKGROUND AND FACTS ===
    doc.add_heading("II. Background and Facts", level=1)

    facts = [
        "Your company provides a B2B SaaS procurement platform to enterprise clients.",
        "You act as a data processor under Art. 28 GDPR, processing procurement data on behalf of your clients (the data controllers).",
        "The data processed includes invoices, purchase orders, and vendor contracts, which contain business contact details of employees at client companies (names, email addresses, job titles, phone numbers).",
        "Your CTO proposes fine-tuning an LLM on this procurement data to develop an \"AI-powered spend analytics\" feature.",
        "The intended feature would predict spending patterns and suggest cost optimizations for clients.",
        "The AI training would use data aggregated from multiple clients' procurement records.",
    ]
    for fact in facts:
        doc.add_paragraph(fact, style="List Bullet")

    doc.add_heading("Key Data Types Involved", level=2)
    data_types = [
        ("Business contact data", "Names, email addresses, job titles, phone numbers of employees at client companies who appear on invoices, POs, and contracts."),
        ("Commercial data", "Invoice amounts, payment terms, product/service descriptions, pricing."),
        ("Vendor information", "Vendor company names, contact persons, contractual terms."),
    ]
    for dtype, desc in data_types:
        p = doc.add_paragraph()
        run = p.add_run(f"{dtype}: ")
        run.bold = True
        p.add_run(desc)

    doc.add_page_break()

    # === III. LEGAL ANALYSIS ===
    doc.add_heading("III. Legal Analysis", level=1)

    # --- A. Controller/Processor ---
    doc.add_heading("A. The Controller/Processor Threshold Issue (Art. 28 GDPR)", level=2)

    doc.add_paragraph(
        "This is the most critical issue in your scenario. Before reaching the legitimate "
        "interest analysis, we must address a threshold question: can a data processor rely "
        "on legitimate interest to process client data for its own purposes?"
    )

    doc.add_heading("1. The Processor's Obligation: Instructions Only", level=3)

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 29",
        "The processor and any person acting under the authority of the controller or of the "
        "processor, who has access to personal data, shall not process those data except on "
        "instructions from the controller, unless required to do so by Union or Member State law."
    )

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 28(3)(a)",
        "[The processor] processes the personal data only on documented instructions from the "
        "controller, including with regard to transfers of personal data to a third country or an "
        "international organisation."
    )

    doc.add_paragraph(
        "These provisions establish a clear rule: processors may only process personal data "
        "according to the controller's documented instructions. Using client data to train your "
        "own AI model — a purpose determined by your company, not by the client — falls outside "
        "any instruction from the controller."
    )

    doc.add_heading("2. Consequence: Deemed Controllership Under Art. 28(10)", level=3)

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 28(10)",
        "Without prejudice to Articles 82, 83 and 84, if a processor infringes this Regulation by "
        "determining the purposes and means of processing, the processor shall be considered to "
        "be a controller in respect of that processing."
    )

    doc.add_paragraph(
        "If your company uses client data for AI model training without explicit authorization "
        "from the controller (your client), you would be \"determining the purposes and means of "
        "processing\" in contravention of Art. 28. The consequence under Art. 28(10) is automatic "
        "re-characterization as a data controller for that processing activity."
    )

    p = doc.add_paragraph()
    run = p.add_run("Practical consequences of deemed controllership include:")
    run.bold = True

    consequences = [
        "Full controller obligations under GDPR (Arts. 5, 6, 12-22, 24-25, 30, 35-36) apply to your AI training activities.",
        "Your company becomes directly liable under Art. 82 (civil liability for damages to data subjects) and Art. 83 (administrative fines up to EUR 20 million or 4% of global turnover).",
        "Breach of the data processing agreement (DPA) with your clients, potentially triggering contractual remedies, indemnification claims, and termination rights.",
        "Reputational damage and loss of client trust — enterprise clients in particular conduct rigorous vendor due diligence on data processing practices.",
    ]
    for c in consequences:
        doc.add_paragraph(c, style="List Bullet")

    doc.add_heading("3. The EDPB's Position on Processor-Turned-Controller", level=3)

    add_citation(
        doc, "VERIFIED", "A", "EDPB Opinion 28/2024, para. 62",
        "The roles and responsibilities of the parties that process personal data in the context "
        "of the development or deployment of an AI model should be assessed before the processing "
        "takes place, in order to define the obligations of the controllers or joint controllers, "
        "and of processors (if any), from the outset."
    )

    doc.add_paragraph(
        "The EDPB has explicitly stated that roles must be defined before processing begins. "
        "A processor that independently decides to use client data for AI training has not merely "
        "committed a procedural violation — it has fundamentally altered its legal position under "
        "GDPR."
    )

    doc.add_page_break()

    # --- B. Purpose Limitation ---
    doc.add_heading("B. Purpose Limitation (Art. 5(1)(b) GDPR)", level=2)

    doc.add_paragraph(
        "Even if the controllership issue were resolved (e.g., through client authorization or "
        "restructuring), AI model training must still comply with the purpose limitation principle."
    )

    doc.add_heading("1. The Original Purpose", level=3)

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 5(1)(b)",
        "Personal data shall be collected for specified, explicit and legitimate purposes and not "
        "further processed in a manner that is incompatible with those purposes."
    )

    doc.add_paragraph(
        "The original purpose for which your company processes procurement data is providing "
        "the SaaS platform service — i.e., managing invoices, purchase orders, and vendor contracts "
        "on behalf of clients. AI model training to develop a new product feature constitutes "
        "further processing for a different purpose."
    )

    doc.add_heading("2. Compatibility Assessment Under Art. 6(4)", level=3)

    doc.add_paragraph(
        "Article 6(4) GDPR requires a compatibility assessment when processing for a purpose "
        "other than that for which data was originally collected. The controller must consider:"
    )

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 6(4)(a)-(e)",
        "(a) any link between the purposes for which the personal data have been collected and "
        "the purposes of the intended further processing; (b) the context in which the personal "
        "data have been collected, in particular regarding the relationship between data subjects "
        "and the controller; (c) the nature of the personal data; (d) the possible consequences of "
        "the intended further processing for data subjects; (e) the existence of appropriate "
        "safeguards, which may include encryption or pseudonymisation."
    )

    doc.add_paragraph("Applying these factors to your scenario:")

    factors = [
        ("Link between purposes (Art. 6(4)(a))", "Moderate. AI-powered spend analytics is related to the procurement domain, but training an LLM is a materially different processing activity from providing a procurement management platform. The model training aggregates data across all clients, which is a qualitative change from per-client processing."),
        ("Context of collection (Art. 6(4)(b))", "Weighs against compatibility. Data subjects (employees at client companies) provided their data in the context of business procurement transactions. They would not reasonably expect their data to be used for training AI models, particularly when aggregated with data from other organizations."),
        ("Nature of the data (Art. 6(4)(c))", "Mixed. The data is primarily business contact information and commercial data, not special categories under Art. 9. However, procurement data can reveal commercially sensitive information about spending patterns, vendor relationships, and pricing — which could be competitively sensitive."),
        ("Consequences for data subjects (Art. 6(4)(d))", "The primary risk is indirect: potential data leakage through model outputs (regurgitation), cross-client data exposure, and loss of control over how personal data is used in the AI model."),
        ("Safeguards (Art. 6(4)(e))", "Can be strengthened. Pseudonymisation, differential privacy, aggregation techniques, and strict access controls could mitigate risks — but must be implemented before the compatibility assessment can conclude favorably."),
    ]

    for factor_name, analysis in factors:
        p = doc.add_paragraph()
        run = p.add_run(f"{factor_name}: ")
        run.bold = True
        p.add_run(analysis)

    add_citation(
        doc, "VERIFIED", "A", "GDPR Recital 50",
        "The processing of personal data for purposes other than those for which the personal data "
        "were initially collected should be allowed only where the processing is compatible with the "
        "purposes for which the personal data were initially collected."
    )

    p = doc.add_paragraph()
    run = p.add_run("Assessment: ")
    run.bold = True
    p.add_run(
        "AI model training is not clearly compatible with the original processing purpose. "
        "The compatibility assessment under Art. 6(4) would require robust safeguards and "
        "a strong justification. Without explicit client authorization, this analysis likely "
        "fails on the context and reasonable expectations factors."
    )

    doc.add_page_break()

    # --- C. Legitimate Interest ---
    doc.add_heading("C. Legitimate Interest Balancing Test (Art. 6(1)(f) GDPR)", level=2)

    doc.add_paragraph(
        "Assuming the controllership issue is resolved and purpose limitation is addressed, "
        "the legitimate interest test under Art. 6(1)(f) requires a three-step assessment."
    )

    doc.add_heading("Step 1: Identification of a Legitimate Interest", level=3)

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 6(1)(f)",
        "Processing is necessary for the purposes of the legitimate interests pursued by the "
        "controller or by a third party, except where such interests are overridden by the "
        "interests or fundamental rights and freedoms of the data subject which require protection "
        "of personal data, in particular where the data subject is a child."
    )

    add_citation(
        doc, "VERIFIED", "A", "EDPB Opinion 28/2024, paras. 67-69",
        "An interest may be regarded as legitimate if the following three cumulative criteria are "
        "met: the interest (1) is lawful; (2) is clearly and precisely articulated; and (3) is real "
        "and present, not speculative. Such interest may cover, for instance, in the development of "
        "an AI model — developing the service of a conversational agent to assist users."
    )

    doc.add_paragraph(
        "Your company's interest in developing an AI-powered spend analytics feature is likely "
        "a legitimate interest. It is:"
    )
    li_items = [
        "Lawful: Developing AI analytics products is a lawful commercial activity.",
        "Clearly articulated: \"Developing an AI model to predict spending patterns and suggest cost optimizations for procurement clients.\"",
        "Real and present: The feature is being actively developed for market deployment, not speculative.",
    ]
    for item in li_items:
        doc.add_paragraph(item, style="List Bullet")

    p = doc.add_paragraph()
    run = p.add_run("Result: ")
    run.bold = True
    run.font.color.rgb = RGBColor(0x00, 0x80, 0x00)
    p.add_run("Step 1 is likely satisfied.")

    doc.add_heading("Step 2: Necessity of the Processing", level=3)

    add_citation(
        doc, "VERIFIED", "A", "EDPB Opinion 28/2024, paras. 70-75",
        "The assessment of necessity entails considering: (1) whether the processing activity will "
        "allow for the pursuit of the legitimate interest; and (2) whether there is no less intrusive "
        "way of pursuing this interest. When assessing whether the condition of necessity is met, SAs "
        "should pay particular attention to the amount of personal data processed and whether it is "
        "proportionate to pursue the legitimate interest at stake."
    )

    doc.add_paragraph(
        "The necessity test presents challenges. Key questions include:"
    )
    necessity_items = [
        "Could synthetic or anonymised data achieve the same result? If procurement patterns can be learned from anonymised/aggregated data, processing personal data is not necessary.",
        "Is the personal data component (business contact details) actually needed for spend analytics? Names, emails, and job titles of individuals appearing on invoices may not be necessary for predicting spending patterns — only the commercial and transactional data may be relevant.",
        "Is there a less intrusive alternative? Pseudonymisation or aggregation before model training could significantly reduce the personal data processed while still achieving the analytics purpose.",
    ]
    for item in necessity_items:
        doc.add_paragraph(item, style="List Bullet")

    p = doc.add_paragraph()
    run = p.add_run("Result: ")
    run.bold = True
    run.font.color.rgb = RGBColor(0xFF, 0x80, 0x00)
    p.add_run(
        "Step 2 is uncertain. A strong argument exists that personal data (especially "
        "business contact details) is not necessary for spend analytics, and less intrusive "
        "alternatives are available."
    )

    doc.add_heading("Step 3: Balancing Test", level=3)

    add_citation(
        doc, "VERIFIED", "A", "GDPR Recital 47",
        "The legitimate interests of a controller [...] may provide a legal basis for processing, "
        "provided that the interests or the fundamental rights and freedoms of the data subject are "
        "not overriding, taking into consideration the reasonable expectations of data subjects "
        "based on their relationship with the controller."
    )

    doc.add_paragraph("The balancing test must weigh the following factors:")

    doc.add_heading("Factors Favoring the Controller's Interest:", level=3)
    favor_items = [
        "The data is business contact information in a B2B context, not sensitive personal data.",
        "The AI feature would benefit clients (cost optimization), creating indirect benefits for data subjects' employers.",
        "Procurement data is commercial in nature, with relatively lower privacy expectations compared to health or financial data of individuals.",
    ]
    for item in favor_items:
        doc.add_paragraph(item, style="List Bullet")

    doc.add_heading("Factors Favoring Data Subjects' Rights:", level=3)

    add_citation(
        doc, "VERIFIED", "A", "EDPB Opinion 28/2024, paras. 91-95",
        "Reasonable expectations play a key role in the balancing test, not least due to the "
        "complexity of the technology used in AI models and the fact that it may be difficult for "
        "data subjects to understand the variety of their potential uses. [...] The data subjects' "
        "reasonable expectations may differ depending on whether the data processed to develop the "
        "model is made public by the data subjects or not."
    )

    against_items = [
        "Reasonable expectations: Employees whose names appear on invoices and POs would not reasonably expect their data to be used for AI model training. Their data was provided in the context of routine business transactions.",
        "Scale and aggregation: The AI training would aggregate data across multiple clients, creating a dataset that no individual data subject authorized or expected.",
        "Loss of control: Once personal data is embedded in an AI model's parameters, exercising data subject rights (erasure, rectification) becomes technically challenging — as the EDPB notes in Opinion 28/2024.",
        "Cross-client data exposure risk: Even with safeguards, there is a residual risk that the model could regurgitate or infer information that crosses client boundaries — a serious concern in B2B contexts where clients are often competitors.",
        "Chilling effect: If processors routinely use client data for their own AI training, this undermines trust in the processor relationship and may deter organizations from outsourcing data processing.",
    ]
    for item in against_items:
        doc.add_paragraph(item, style="List Bullet")

    p = doc.add_paragraph()
    run = p.add_run("Result: ")
    run.bold = True
    run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
    p.add_run(
        "Step 3 likely fails without significant mitigating measures. The combination "
        "of low reasonable expectations, cross-client aggregation, and the processor relationship "
        "context weighs heavily against the controller's interest."
    )

    doc.add_page_break()

    # --- D. EDPB Position ---
    doc.add_heading("D. EDPB Position on AI and Personal Data", level=2)

    doc.add_heading("1. EDPB Opinion 28/2024 (Adopted 17 December 2024)", level=3)

    doc.add_paragraph(
        "This is the EDPB's landmark guidance on processing personal data for AI model development "
        "and deployment. Key findings relevant to your scenario:"
    )

    add_citation(
        doc, "VERIFIED", "A", "EDPB Opinion 28/2024, Executive Summary",
        "AI models trained with personal data cannot, in all cases, be considered anonymous. For an "
        "AI model to be considered anonymous, both (1) the likelihood of direct (including "
        "probabilistic) extraction of personal data regarding individuals whose personal data were "
        "used to develop the model and (2) the likelihood of obtaining, intentionally or not, such "
        "personal data from queries, should be insignificant."
    )

    key_findings = [
        ("AI models are not automatically anonymous", "Even after training, personal data may remain \"absorbed\" in model parameters and may be extractable through various attack vectors (membership inference, model inversion, regurgitation). Your AI model trained on procurement data cannot be assumed to be anonymous."),
        ("Roles must be determined upfront", "The EDPB emphasizes that controller/processor roles must be \"assessed before the processing takes place\" (para. 62). Retrospective role determination after AI training has begun is not acceptable."),
        ("Mitigating measures are essential but not sufficient alone", "The EDPB provides a non-exhaustive list of technical and organizational measures (pseudonymisation, differential privacy, opt-out mechanisms, transparency measures) but stresses these must be assessed on a case-by-case basis and cannot automatically tip the balancing test."),
        ("Purpose specificity is required", "The EDPB states that the purpose of processing must be \"clearly and specifically identified\" (para. 64). Generic purposes like \"AI development\" are insufficient — the specific functionality, intended deployment context, and whether the model is for internal or commercial use must be documented."),
    ]

    for finding_title, finding_text in key_findings:
        p = doc.add_paragraph()
        run = p.add_run(f"{finding_title}: ")
        run.bold = True
        p.add_run(finding_text)

    doc.add_heading("2. Garante v OpenAI Decision (December 2024)", level=3)

    add_citation(
        doc, "VERIFIED", "B", "Garante per la protezione dei dati personali, Decision of 20 December 2024",
        "The Garante issued the EU's first-ever fine against a generative AI company, fining OpenAI "
        "EUR 15 million for training ChatGPT on personal data without a legal basis, failing to "
        "provide transparency about data use, lacking age verification for users under 13, and "
        "failing to notify the Garante of a March 2023 data breach."
    )

    doc.add_paragraph(
        "While OpenAI's situation differs (web scraping at massive scale), this enforcement action "
        "confirms that DPAs are actively scrutinizing AI training practices and will not hesitate "
        "to impose significant fines for inadequate legal bases."
    )

    doc.add_heading("3. Clearview AI Enforcement Actions", level=3)

    doc.add_paragraph(
        "Multiple DPAs (Italy, France, Greece, Netherlands) have fined Clearview AI for scraping "
        "publicly available images to train facial recognition AI. The Dutch DPA's EUR 30.5 million "
        "fine reinforced that \"publicly available\" data does not equate to freely usable data for "
        "AI training. While this involves biometric data (a special category), the principle — that "
        "data available in one context cannot be freely repurposed for AI training — applies broadly."
    )

    doc.add_page_break()

    # --- E. Digital Omnibus ---
    doc.add_heading("E. Digital Omnibus Impact (COM(2025) 837)", level=2)

    doc.add_paragraph(
        "The European Commission's Digital Omnibus proposal (COM(2025) 837 final, published "
        "19 November 2025) proposes significant amendments to the GDPR that would directly "
        "affect the analysis above. As a legislative proposal, it is not yet law and its final "
        "form may differ substantially after European Parliament and Council negotiations."
    )

    doc.add_heading("1. AI Development as Explicit Legitimate Interest", level=3)

    add_citation(
        doc, "VERIFIED", "B", "COM(2025) 837, Recital (30)",
        "Trustworthy AI is key in providing for economic growth and supporting innovation with "
        "socially beneficial outcomes. The development and use of AI systems and the underlying "
        "models such as large language models and generative video models rely on data, including "
        "personal data, in various phases in the AI lifecycle, such as the training, testing and "
        "validation phase [...] The processing of personal data in this context may therefore be "
        "carried out for purposes of a legitimate interest within the meaning of Article 6 of "
        "Regulation (EU) 2016/679, where appropriate."
    )

    doc.add_paragraph(
        "This recital would create an explicit legislative endorsement of AI development as "
        "a legitimate interest. However, it expressly does not eliminate the obligation to satisfy "
        "all other conditions of Art. 6(1)(f) — including the balancing test."
    )

    doc.add_heading("2. Enhanced Balancing Test Guidance for AI", level=3)

    add_citation(
        doc, "VERIFIED", "B", "COM(2025) 837, Recital (31)",
        "When the controller [...] is balancing the legitimate interest pursued by the controller "
        "or a third party and the interests, rights and freedoms of the data subject, consideration "
        "should be given to whether the interest pursued by the controller is beneficial for the "
        "data subject and society at large [...] Consideration should also [...] be given to "
        "reasonable expectations of the data subject based on their relationship with the "
        "controller, appropriate safeguards to minimise the impact on data subjects' rights such as "
        "providing enhanced transparency to data subjects, providing an unconditional right to object "
        "to the processing of their personal data, respecting technical indications embedded in a "
        "service limiting the use of data for AI development by third parties, the use of other "
        "state of the art privacy preserving techniques for AI training and appropriate technical "
        "measures to effectively minimise risks resulting, for example, from regurgitation, data "
        "leakage and other intended or foreseeable actions."
    )

    doc.add_heading("3. Special Categories Derogation for AI (Recital 33)", level=3)

    add_citation(
        doc, "VERIFIED", "B", "COM(2025) 837, Recital (33)",
        "The development of certain AI systems and AI models may involve the collection of large "
        "amounts of data, including personal data and special categories thereof. [...] In order "
        "not to disproportionately hinder the development and operation of AI [...] derogating from "
        "the prohibition on processing special categories of personal data under Article 9(2) of "
        "Regulation (EU) 2016/679 should be allowed."
    )

    doc.add_heading("4. Purpose Limitation Clarification", level=3)

    doc.add_paragraph(
        "The Digital Omnibus also proposes to amend Art. 5(1)(b) to clarify that further processing "
        "for scientific or historical research purposes or statistical purposes is compatible with "
        "the initial purposes, independent of the conditions of Art. 6(4). This could benefit AI "
        "development if it can be characterized as scientific research, though commercial AI "
        "product development is unlikely to qualify."
    )

    doc.add_heading("5. Impact Assessment: What Changes and What Doesn't", level=3)

    doc.add_paragraph("If the Digital Omnibus is adopted as proposed:")

    changes_items = [
        "Changes: AI development would be explicitly recognized as a legitimate interest, providing stronger legal certainty for Step 1 of the balancing test. The balancing test guidance would be codified in legislation (not just EDPB guidance).",
        "Does NOT change: The Art. 28 controller/processor issue remains. A processor still cannot unilaterally decide to use client data for AI training. The three-part balancing test still applies in full. The purpose limitation principle still applies.",
        "New safeguards required: Enhanced transparency, unconditional right to object, privacy-preserving techniques, and measures against regurgitation would become legislatively mandated considerations.",
    ]
    for item in changes_items:
        doc.add_paragraph(item, style="List Bullet")

    p = doc.add_paragraph()
    run = p.add_run("Important caveat: ")
    run.bold = True
    p.add_run(
        "COM(2025) 837 is a proposal. It must pass through the European Parliament and Council "
        "ordinary legislative procedure, which typically takes 18-36 months. The final text may "
        "differ significantly. The EDPB-EDPS Joint Opinion 1/2026 has already expressed concerns "
        "about certain relaxations in the proposal. Do not plan compliance strategies based solely "
        "on the proposed text."
    )

    doc.add_page_break()

    # === IV. RISK ASSESSMENT ===
    doc.add_heading("IV. Risk Assessment Summary", level=1)

    # Risk table
    table = doc.add_table(rows=6, cols=3)
    table.style = "Light Grid Accent 1"
    headers = ["Risk Area", "Risk Level", "Key Issue"]
    for i, header in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = header
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True

    risks = [
        ("Art. 28 Violation (Processor exceeding mandate)", "HIGH", "Deemed controllership, contractual breach, client loss"),
        ("Art. 5(1)(b) Purpose Limitation", "HIGH", "AI training likely incompatible with original purpose without consent"),
        ("Art. 6(1)(f) Legitimate Interest (if restructured)", "MEDIUM-HIGH", "Balancing test fails on reasonable expectations"),
        ("DPA Enforcement", "MEDIUM", "Active enforcement trend against AI training (OpenAI, Clearview)"),
        ("Contractual/Reputational", "HIGH", "Enterprise client DPA breach, trust erosion"),
    ]
    for row_idx, (area, level, issue) in enumerate(risks, 1):
        table.rows[row_idx].cells[0].text = area
        table.rows[row_idx].cells[1].text = level
        table.rows[row_idx].cells[2].text = issue

    doc.add_page_break()

    # === V. RECOMMENDATIONS ===
    doc.add_heading("V. Recommendations", level=1)

    doc.add_heading("Option A: Client-Authorized AI Training (Recommended)", level=2)
    option_a = [
        "Amend DPAs with clients to explicitly authorize the use of pseudonymised/aggregated procurement data for AI model training.",
        "Position the AI training as a feature within the existing service (spend analytics as a value-add), so clients authorize it as part of the service relationship.",
        "Implement a clear opt-in mechanism where clients affirmatively consent to contributing (anonymised/pseudonymised) data to the AI training pool.",
        "Provide clients with transparency about what data is used, how the model works, and what safeguards are in place.",
        "Ensure clients update their own privacy notices to inform data subjects about AI-related processing.",
    ]
    for item in option_a:
        doc.add_paragraph(item, style="List Number")

    doc.add_heading("Option B: Anonymisation-First Approach", level=2)
    option_b = [
        "Implement robust anonymisation or pseudonymisation before any AI training occurs.",
        "Strip all personal identifiers (names, emails, job titles, phone numbers) from the training data, retaining only commercial/transactional patterns.",
        "If the data is truly anonymised (per the EDPB's high standard in Opinion 28/2024), GDPR does not apply to the training process.",
        "Document the anonymisation process thoroughly — the EDPB requires evidence that extraction and query-based identification risks are \"insignificant.\"",
    ]
    for item in option_b:
        doc.add_paragraph(item, style="List Number")

    doc.add_heading("Option C: Separate Controller Relationship (Alternative)", level=2)
    option_c = [
        "Restructure the AI training activity as a separate service where your company acts as an independent controller.",
        "Obtain a separate legal basis (likely consent or legitimate interest) directly from data subjects or through the client relationship.",
        "This requires careful DPA structuring, clear information provision, and may require separate consent from data subjects.",
    ]
    for item in option_c:
        doc.add_paragraph(item, style="List Number")

    doc.add_heading("Technical Safeguards (Applicable to All Options)", level=2)
    safeguards = [
        "Differential privacy techniques during model training.",
        "Data minimisation: Remove personal identifiers before training; use only commercial data patterns.",
        "Client data segregation: Ensure model outputs cannot leak cross-client information.",
        "Regular testing against extraction attacks (membership inference, model inversion, regurgitation).",
        "Unconditional right to object mechanism (as recommended by the Digital Omnibus proposal).",
        "DPIA under Art. 35 — AI model training at this scale likely triggers a mandatory impact assessment.",
    ]
    for item in safeguards:
        doc.add_paragraph(item, style="List Bullet")

    doc.add_page_break()

    # === VI. CONCLUSION ===
    doc.add_heading("VI. Conclusion", level=1)

    doc.add_paragraph(
        "Your company cannot, under the current GDPR framework, simply rely on legitimate "
        "interest (Art. 6(1)(f)) as a data processor to train an AI model on client procurement "
        "data for its own purposes. The fundamental obstacle is the controller/processor framework "
        "under Art. 28: a processor that determines its own purpose for processing becomes a "
        "controller, with all the legal exposure that entails."
    )

    doc.add_paragraph(
        "Even if the controllership issue is resolved through client authorization, the "
        "legitimate interest analysis faces significant challenges at Steps 2 (necessity) and "
        "3 (balancing), primarily due to: (a) the availability of less intrusive alternatives "
        "(anonymisation/pseudonymisation); (b) the low reasonable expectations of data subjects "
        "whose business contact information would be used for AI training; and (c) cross-client "
        "data aggregation risks."
    )

    doc.add_paragraph(
        "The Digital Omnibus proposal (COM(2025) 837) would, if adopted, provide a more "
        "favorable framework by explicitly recognizing AI development as a legitimate interest — "
        "but it would not eliminate the need for the balancing test, and it does not address the "
        "processor/controller threshold issue."
    )

    p = doc.add_paragraph()
    run = p.add_run("We recommend Option A (Client-Authorized AI Training) ")
    run.bold = True
    p.add_run(
        "combined with robust anonymisation/pseudonymisation measures as the most legally "
        "defensible path forward. This approach respects the processor relationship, ensures "
        "client transparency, and provides the strongest foundation for demonstrating GDPR "
        "compliance."
    )

    doc.add_paragraph("")

    # === DISCLAIMER ===
    doc.add_heading("Disclaimer", level=1)

    disclaimer = doc.add_paragraph(
        "This legal analysis memo is provided for informational purposes only and does not constitute "
        "legal advice. The analysis is based on the General Data Protection Regulation (EU) "
        "2016/679, EDPB guidance current as of the date of this memo, and the proposed Digital "
        "Omnibus (COM(2025) 837) which has not yet been adopted. The legal landscape for AI and "
        "data protection is evolving rapidly. For specific matters relating to your organization's "
        "compliance obligations, please consult qualified legal counsel in the relevant EU "
        "jurisdiction(s)."
    )
    disclaimer.style = "Quote"

    # === SOURCES ===
    doc.add_heading("Sources Cited", level=1)
    sources = [
        "[Grade A] GDPR — Articles 5, 6, 28, 29; Recitals 47, 50",
        "[Grade A] EDPB Opinion 28/2024 on certain data protection aspects related to the processing of personal data in the context of AI models (adopted 17 December 2024)",
        "[Grade A] EDPB Guidelines 1/2024 on processing of personal data based on Article 6(1)(f) GDPR (adopted 8 October 2024)",
        "[Grade A] CJEU Case C-252/21, Meta v. Bundeskartellamt (4 July 2023)",
        "[Grade A] CJEU Case C-26/22, SCHUFA Holding (7 December 2023)",
        "[Grade B] COM(2025) 837 final — Digital Legislation Omnibus (proposed 19 November 2025)",
        "[Grade B] Garante v OpenAI (ChatGPT) — EUR 15 Million (20 December 2024)",
        "[Grade B] AP Netherlands v Clearview AI — EUR 30.5 Million (16 May 2024)",
    ]
    for s in sources:
        doc.add_paragraph(s, style="List Bullet")

    path = OUTPUT_DIR / "Legal_Opinion_AI_Training_GDPR_EN.docx"
    doc.save(str(path))
    print(f"English opinion saved: {path}")
    return path


def generate_korean_opinion():
    doc = Document()
    setup_styles(doc)
    add_header_footer(doc, "법률 분석 메모 — GDPR 하에서의 AI 모델 학습")

    # === TITLE PAGE ===
    for _ in range(4):
        doc.add_paragraph("")

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("법률 분석 메모")
    run.bold = True
    run.font.size = Pt(28)
    run.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(
        "조달 데이터를 활용한 AI 모델 학습의 적법성 검토\n"
        "유럽연합 일반개인정보보호규정(GDPR, EU 2016/679) 분석"
    )
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    doc.add_paragraph("")

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run(f"작성일: {date.today().strftime('%Y년 %m월 %d일')}\n").font.size = Pt(11)
    meta.add_run("문서번호: GDPR-2026-LO-001-KR\n").font.size = Pt(11)
    meta.add_run("비밀등급: 대외비\n").font.size = Pt(11)
    meta.add_run("생성 주체: Jinju Legal Orchestrator — EU 데이터 보호 스페셜리스트 Kim De Bruyne (김덕배)").font.size = Pt(11)

    doc.add_page_break()

    # === TOC ===
    doc.add_heading("목차", level=1)
    toc_items = [
        "I.   요약 (Executive Summary)",
        "II.  사실관계",
        "III. 법률 분석",
        "     A. 컨트롤러/프로세서 지위 문제 (Art. 28 GDPR)",
        "     B. 목적 제한 원칙 (Art. 5(1)(b) GDPR)",
        "     C. 정당한 이익 균형 테스트 (Art. 6(1)(f) GDPR)",
        "     D. AI와 개인정보에 대한 EDPB 입장",
        "     E. 디지털 옴니버스 영향 (COM(2025) 837)",
        "IV.  리스크 평가 요약",
        "V.   권고사항",
        "VI.  결론",
        "     면책 조항",
    ]
    for item in toc_items:
        doc.add_paragraph(item)
    doc.add_page_break()

    # === I. EXECUTIVE SUMMARY ===
    doc.add_heading("I. 요약 (Executive Summary)", level=1)

    doc.add_paragraph(
        "귀사는 기업 고객을 대리하여 조달 데이터(송장, 구매 주문서, 공급업체 계약서)를 처리하는 "
        "B2B SaaS 플랫폼을 운영하고 있습니다. 귀사는 GDPR 제28조에 따른 데이터 처리자(processor) "
        "지위에 있습니다. 귀사의 CTO는 이 데이터를 활용하여 대규모 언어 모델(LLM)을 파인튜닝하여 "
        "\"AI 기반 지출 분석\" 기능 — 지출 패턴 예측 및 비용 최적화 제안 — 을 개발하고자 합니다."
    )

    doc.add_paragraph(
        "분석 결과, 이 제안은 현행 GDPR 체계 하에서 상당한 법적 장애에 직면합니다. 핵심 문제는 "
        "정당한 이익 테스트 자체가 아니라, 선행적(threshold) 문제입니다: 데이터 처리자로서 귀사는 "
        "고객 데이터에 대한 새로운 처리 목적을 일방적으로 결정할 수 없습니다. 이를 행할 경우 "
        "GDPR 제28조 제10항이 발동되어 귀사가 해당 처리에 대한 컨트롤러(controller)로 재분류되며, "
        "이에 따른 모든 의무와 책임이 수반됩니다."
    )

    p = doc.add_paragraph()
    run = p.add_run("핵심 결론: ")
    run.bold = True
    p.add_run(
        "정당한 이익(Art. 6(1)(f))에 의존하는 것은 법적으로 문제가 있습니다. 그 이유는: "
        "(1) 프로세서는 처리를 위한 법적 근거를 원용할 수 없으며 — 컨트롤러만 가능합니다; "
        "(2) 고객 데이터를 자체 AI 학습 목적으로 사용하면 Art. 28(10)에 따라 귀사가 컨트롤러로 "
        "전환되어 상당한 컴플라이언스 리스크가 발생합니다; "
        "(3) 컨트롤러로 구조를 변경하더라도, 목적 제한 원칙과 정당한 이익 균형 테스트는 데이터의 "
        "성격과 정보주체의 합리적 기대를 고려할 때 상당한 장애물을 제시합니다."
    )

    doc.add_page_break()

    # === II. FACTS ===
    doc.add_heading("II. 사실관계", level=1)

    facts = [
        "귀사는 기업 고객에게 B2B SaaS 조달 플랫폼을 제공합니다.",
        "귀사는 GDPR Art. 28에 따른 데이터 처리자(processor)로서, 고객(데이터 컨트롤러)을 대리하여 조달 데이터를 처리합니다.",
        "처리되는 데이터에는 송장, 구매 주문서, 공급업체 계약서가 포함되며, 이는 고객 기업 직원의 업무용 연락처 정보(성명, 이메일 주소, 직책, 전화번호)를 포함합니다.",
        "귀사의 CTO는 이 조달 데이터로 LLM을 파인튜닝하여 \"AI 기반 지출 분석\" 기능을 개발할 것을 제안합니다.",
        "해당 기능은 고객사의 지출 패턴을 예측하고 비용 최적화를 제안하는 것을 목적으로 합니다.",
        "AI 학습에는 다수 고객의 조달 기록에서 집계된 데이터가 사용될 예정입니다.",
    ]
    for fact in facts:
        doc.add_paragraph(fact, style="List Bullet")

    doc.add_page_break()

    # === III. LEGAL ANALYSIS ===
    doc.add_heading("III. 법률 분석", level=1)

    # --- A. Controller/Processor ---
    doc.add_heading("A. 컨트롤러/프로세서 지위 문제 (Art. 28 GDPR)", level=2)

    doc.add_paragraph(
        "이것이 귀사 시나리오에서 가장 핵심적인 쟁점입니다. 정당한 이익 분석에 도달하기 전에, "
        "선행적 문제를 다루어야 합니다: 데이터 처리자가 자체 목적으로 고객 데이터를 처리하기 위해 "
        "정당한 이익에 의존할 수 있는가?"
    )

    doc.add_heading("1. 프로세서의 의무: 오직 지시에 따른 처리만 가능", level=3)

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 29",
        "The processor and any person acting under the authority of the controller or of the "
        "processor, who has access to personal data, shall not process those data except on "
        "instructions from the controller, unless required to do so by Union or Member State law."
    )

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 28(3)(a)",
        "[The processor] processes the personal data only on documented instructions from the "
        "controller, including with regard to transfers of personal data to a third country or an "
        "international organisation."
    )

    doc.add_paragraph(
        "이 규정들은 명확한 원칙을 수립합니다: 프로세서는 컨트롤러의 문서화된 지시에 따라서만 "
        "개인정보를 처리할 수 있습니다. 고객 데이터를 사용하여 자체 AI 모델을 학습시키는 것은 "
        "— 고객이 아닌 귀사가 결정한 목적 — 컨트롤러의 어떠한 지시에도 해당하지 않습니다."
    )

    doc.add_heading("2. 결과: Art. 28(10)에 따른 간주 컨트롤러 전환", level=3)

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 28(10)",
        "Without prejudice to Articles 82, 83 and 84, if a processor infringes this Regulation by "
        "determining the purposes and means of processing, the processor shall be considered to "
        "be a controller in respect of that processing."
    )

    doc.add_paragraph(
        "귀사가 컨트롤러(고객)의 명시적 승인 없이 고객 데이터를 AI 모델 학습에 사용하는 경우, "
        "귀사는 Art. 28을 위반하여 \"처리의 목적과 수단을 결정\"하게 됩니다. Art. 28(10)에 따른 "
        "결과는 해당 처리 활동에 대한 데이터 컨트롤러로의 자동적 재분류입니다."
    )

    p = doc.add_paragraph()
    run = p.add_run("간주 컨트롤러 전환의 실질적 결과:")
    run.bold = True

    consequences = [
        "GDPR 상의 컨트롤러 의무 전면 적용 (Art. 5, 6, 12-22, 24-25, 30, 35-36) — AI 학습 활동에 적용됨.",
        "Art. 82(정보주체에 대한 민사 손해배상 책임) 및 Art. 83(최대 2,000만 유로 또는 글로벌 매출의 4%의 과징금)에 따른 직접적 책임.",
        "고객과의 데이터 처리 계약(DPA) 위반 — 계약상 구제수단, 손해배상 청구, 해지권 등을 발동시킬 수 있음.",
        "평판 훼손 및 고객 신뢰 상실 — 특히 기업 고객은 데이터 처리 관행에 대한 엄격한 공급업체 실사를 수행함.",
    ]
    for c in consequences:
        doc.add_paragraph(c, style="List Bullet")

    doc.add_page_break()

    # --- B. Purpose Limitation ---
    doc.add_heading("B. 목적 제한 원칙 (Art. 5(1)(b) GDPR)", level=2)

    doc.add_paragraph(
        "컨트롤러 지위 문제가 해결되더라도(예: 고객 승인 또는 구조 변경을 통해), "
        "AI 모델 학습은 여전히 목적 제한 원칙을 준수해야 합니다."
    )

    add_citation(
        doc, "VERIFIED", "A", "GDPR Article 5(1)(b)",
        "Personal data shall be collected for specified, explicit and legitimate purposes and not "
        "further processed in a manner that is incompatible with those purposes."
    )

    doc.add_paragraph(
        "원래의 처리 목적은 SaaS 플랫폼 서비스 제공 — 즉, 고객을 대리하여 송장, 구매 주문서, "
        "공급업체 계약서를 관리하는 것입니다. 새로운 제품 기능 개발을 위한 AI 모델 학습은 "
        "다른 목적을 위한 추가 처리에 해당합니다."
    )

    doc.add_heading("양립성 평가 (Art. 6(4) 적용)", level=3)

    doc.add_paragraph("Art. 6(4)에 따른 양립성 평가 시 고려해야 할 요소:")

    factors = [
        ("목적 간 연관성 (Art. 6(4)(a))", "보통. AI 기반 지출 분석은 조달 영역과 관련이 있으나, LLM 학습은 조달 관리 플랫폼 제공과 실질적으로 다른 처리 활동임."),
        ("수집 맥락 (Art. 6(4)(b))", "양립성에 불리. 정보주체(고객사 직원)는 일상적 업무 거래 맥락에서 데이터를 제공함. 특히 타 조직의 데이터와 집계되어 AI 모델 학습에 사용될 것이라고 합리적으로 기대하지 않음."),
        ("데이터의 성격 (Art. 6(4)(c))", "혼합적. 주로 업무용 연락처와 상업적 데이터로 Art. 9의 민감정보에 해당하지 않으나, 지출 패턴, 공급업체 관계, 가격 등 상업적으로 민감한 정보를 포함."),
        ("정보주체에 대한 결과 (Art. 6(4)(d))", "모델 출력을 통한 잠재적 데이터 유출(재생성), 교차 고객 데이터 노출, 개인정보 사용에 대한 통제력 상실 위험."),
        ("안전조치 (Art. 6(4)(e))", "강화 가능. 가명처리, 차분 프라이버시, 집계 기법, 엄격한 접근 통제 등이 위험을 완화할 수 있으나, 양립성 평가가 긍정적으로 결론나기 전에 구현되어야 함."),
    ]

    for factor_name, analysis in factors:
        p = doc.add_paragraph()
        run = p.add_run(f"{factor_name}: ")
        run.bold = True
        p.add_run(analysis)

    doc.add_page_break()

    # --- C. Legitimate Interest ---
    doc.add_heading("C. 정당한 이익 균형 테스트 (Art. 6(1)(f) GDPR)", level=2)

    doc.add_paragraph(
        "컨트롤러 지위 문제가 해결되고 목적 제한이 충족된다고 가정할 때, "
        "Art. 6(1)(f)의 정당한 이익 테스트는 3단계 평가를 요구합니다."
    )

    doc.add_heading("1단계: 정당한 이익의 식별", level=3)

    add_citation(
        doc, "VERIFIED", "A", "EDPB Opinion 28/2024, paras. 67-69",
        "An interest may be regarded as legitimate if the following three cumulative criteria are "
        "met: the interest (1) is lawful; (2) is clearly and precisely articulated; and (3) is real "
        "and present, not speculative."
    )

    doc.add_paragraph(
        "귀사의 AI 기반 지출 분석 기능 개발 이익은 정당한 이익에 해당할 가능성이 높습니다."
    )

    p = doc.add_paragraph()
    run = p.add_run("결과: ")
    run.bold = True
    run.font.color.rgb = RGBColor(0x00, 0x80, 0x00)
    p.add_run("1단계는 충족될 가능성이 높습니다.")

    doc.add_heading("2단계: 처리의 필요성", level=3)

    add_citation(
        doc, "VERIFIED", "A", "EDPB Opinion 28/2024, paras. 70-75",
        "The assessment of necessity entails considering: (1) whether the processing activity will "
        "allow for the pursuit of the legitimate interest; and (2) whether there is no less intrusive "
        "way of pursuing this interest."
    )

    necessity_items = [
        "합성 데이터 또는 익명화된 데이터로 동일한 결과를 달성할 수 있는가?",
        "개인정보 요소(업무용 연락처)가 실제로 지출 분석에 필요한가? 지출 패턴 예측에는 상업적/거래 데이터만 필요할 수 있음.",
        "덜 침해적인 대안이 있는가? 모델 학습 전 가명처리 또는 집계가 상당 부분의 개인정보 처리를 줄일 수 있음.",
    ]
    for item in necessity_items:
        doc.add_paragraph(item, style="List Bullet")

    p = doc.add_paragraph()
    run = p.add_run("결과: ")
    run.bold = True
    run.font.color.rgb = RGBColor(0xFF, 0x80, 0x00)
    p.add_run("2단계는 불확실합니다. 개인정보(특히 업무용 연락처)가 지출 분석에 불필요하며, 덜 침해적인 대안이 존재한다는 강한 논거가 있습니다.")

    doc.add_heading("3단계: 균형 테스트", level=3)

    doc.add_paragraph("균형 테스트에서 고려해야 할 요소:")

    doc.add_heading("컨트롤러의 이익에 유리한 요소:", level=3)
    favor_items = [
        "데이터는 B2B 맥락에서의 업무용 연락처로, 민감 개인정보가 아닙니다.",
        "AI 기능은 고객에게 혜택(비용 최적화)을 제공하며, 정보주체의 고용주에게 간접적 혜택을 줍니다.",
        "조달 데이터는 상업적 성격으로, 건강 또는 개인 재무 데이터에 비해 프라이버시 기대가 상대적으로 낮습니다.",
    ]
    for item in favor_items:
        doc.add_paragraph(item, style="List Bullet")

    doc.add_heading("정보주체의 권리에 유리한 요소:", level=3)
    against_items = [
        "합리적 기대: 송장과 PO에 이름이 등장하는 직원들은 자신의 데이터가 AI 모델 학습에 사용될 것이라고 합리적으로 기대하지 않습니다.",
        "규모와 집계: AI 학습은 다수 고객의 데이터를 집계하며, 이는 개별 정보주체가 승인하거나 기대한 데이터셋이 아닙니다.",
        "통제력 상실: 개인정보가 AI 모델의 파라미터에 내장되면, 정보주체 권리(삭제, 정정) 행사가 기술적으로 어려워집니다.",
        "교차 고객 데이터 노출 위험: 안전조치에도 불구하고, 모델이 고객 경계를 넘는 정보를 재생성하거나 추론할 수 있는 잔여 위험이 존재합니다.",
        "위축 효과: 프로세서가 일상적으로 고객 데이터를 자체 AI 학습에 사용하면, 프로세서 관계에 대한 신뢰가 훼손됩니다.",
    ]
    for item in against_items:
        doc.add_paragraph(item, style="List Bullet")

    p = doc.add_paragraph()
    run = p.add_run("결과: ")
    run.bold = True
    run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
    p.add_run(
        "3단계는 상당한 완화 조치 없이는 통과하기 어렵습니다. 낮은 합리적 기대, 교차 고객 "
        "집계, 프로세서 관계 맥락의 조합이 컨트롤러의 이익에 크게 불리하게 작용합니다."
    )

    doc.add_page_break()

    # --- D. EDPB Position ---
    doc.add_heading("D. AI와 개인정보에 대한 EDPB 입장", level=2)

    doc.add_heading("1. EDPB 의견 28/2024 (2024년 12월 17일 채택)", level=3)

    doc.add_paragraph(
        "AI 모델 개발 및 배포에서의 개인정보 처리에 대한 EDPB의 획기적인 가이던스입니다. "
        "귀사 시나리오에 관련된 주요 결론:"
    )

    key_findings = [
        ("AI 모델은 자동적으로 익명이 아님", "학습 후에도 개인정보가 모델 파라미터에 \"흡수\"되어 남아 있을 수 있으며, 다양한 공격 벡터(멤버십 추론, 모델 역전, 재생성)를 통해 추출될 수 있습니다."),
        ("역할은 사전에 결정되어야 함", "EDPB는 컨트롤러/프로세서 역할이 \"처리가 이루어지기 전에 평가되어야\" 한다고 강조합니다(문단 62)."),
        ("완화 조치는 필수적이나 그 자체로 충분하지 않음", "EDPB는 기술적/조직적 조치의 비한정적 목록을 제공하나, 이것만으로 균형 테스트를 자동적으로 충족시킬 수 없다고 강조합니다."),
        ("목적의 구체성이 필요", "EDPB는 처리 목적이 \"명확하고 구체적으로 식별\"되어야 한다고 명시합니다. \"AI 개발\"과 같은 일반적 목적은 불충분합니다."),
    ]

    for finding_title, finding_text in key_findings:
        p = doc.add_paragraph()
        run = p.add_run(f"{finding_title}: ")
        run.bold = True
        p.add_run(finding_text)

    doc.add_heading("2. 이탈리아 Garante v OpenAI 결정 (2024년 12월)", level=3)

    doc.add_paragraph(
        "이탈리아 개인정보보호 감독기관(Garante)이 생성 AI 기업에 대해 EU 최초로 부과한 과징금입니다. "
        "OpenAI에 대해 법적 근거 없이 ChatGPT를 개인정보로 학습시킨 것에 대해 1,500만 유로의 "
        "과징금을 부과했습니다. OpenAI의 상황(대규모 웹 스크래핑)과 다르지만, 이 집행 조치는 "
        "DPA들이 AI 학습 관행을 적극적으로 조사하고 있음을 확인합니다."
    )

    doc.add_page_break()

    # --- E. Digital Omnibus ---
    doc.add_heading("E. 디지털 옴니버스 영향 (COM(2025) 837)", level=2)

    doc.add_paragraph(
        "유럽위원회의 디지털 옴니버스 제안(COM(2025) 837 final, 2025년 11월 19일 공표)은 "
        "위 분석에 직접적으로 영향을 미칠 GDPR의 중대한 개정안을 제안하고 있습니다. "
        "다만 입법안(proposal)으로서 아직 법률이 아니며, 유럽의회 및 이사회 협상 후 최종 "
        "형태가 상당히 달라질 수 있습니다."
    )

    doc.add_heading("1. AI 개발을 명시적 정당한 이익으로 인정", level=3)

    add_citation(
        doc, "VERIFIED", "B", "COM(2025) 837, Recital (30)",
        "Trustworthy AI is key in providing for economic growth and supporting innovation with "
        "socially beneficial outcomes. The development and use of AI systems and the underlying "
        "models such as large language models and generative video models rely on data, including "
        "personal data, in various phases in the AI lifecycle, such as the training, testing and "
        "validation phase [...] The processing of personal data in this context may therefore be "
        "carried out for purposes of a legitimate interest within the meaning of Article 6 of "
        "Regulation (EU) 2016/679, where appropriate."
    )

    doc.add_heading("2. AI를 위한 강화된 균형 테스트 가이던스", level=3)

    add_citation(
        doc, "VERIFIED", "B", "COM(2025) 837, Recital (31)",
        "When the controller [...] is balancing the legitimate interest pursued by the controller "
        "or a third party and the interests, rights and freedoms of the data subject, consideration "
        "should be given to whether the interest pursued by the controller is beneficial for the "
        "data subject and society at large [...] Consideration should also [...] be given to "
        "reasonable expectations of the data subject based on their relationship with the "
        "controller, appropriate safeguards to minimise the impact on data subjects' rights such as "
        "providing enhanced transparency to data subjects, providing an unconditional right to object "
        "to the processing of their personal data, respecting technical indications embedded in a "
        "service limiting the use of data for AI development by third parties, the use of other "
        "state of the art privacy preserving techniques for AI training and appropriate technical "
        "measures to effectively minimise risks resulting, for example, from regurgitation, data "
        "leakage and other intended or foreseeable actions."
    )

    doc.add_heading("3. 채택 시 변경 사항 및 변경되지 않는 사항", level=3)

    changes_items = [
        "변경 사항: AI 개발이 정당한 이익으로 명시적으로 인정되어, 균형 테스트 1단계에 더 강한 법적 확실성이 제공됩니다.",
        "변경되지 않는 사항: Art. 28 컨트롤러/프로세서 문제는 그대로 유지됩니다. 프로세서는 여전히 일방적으로 고객 데이터를 AI 학습에 사용할 수 없습니다. 3단계 균형 테스트는 여전히 전면 적용됩니다.",
        "새로운 안전조치 요건: 강화된 투명성, 무조건적 거부권, 프라이버시 보호 기술, 재생성 방지 조치가 입법적으로 의무화된 고려사항이 됩니다.",
    ]
    for item in changes_items:
        doc.add_paragraph(item, style="List Bullet")

    p = doc.add_paragraph()
    run = p.add_run("중요 유의사항: ")
    run.bold = True
    p.add_run(
        "COM(2025) 837은 제안(proposal)입니다. 유럽의회와 이사회의 통상 입법 절차를 "
        "거쳐야 하며, 이는 통상 18-36개월이 소요됩니다. 최종 텍스트는 상당히 달라질 수 "
        "있습니다. 제안 텍스트만을 근거로 컴플라이언스 전략을 수립하지 마십시오."
    )

    doc.add_page_break()

    # === IV. RISK ASSESSMENT ===
    doc.add_heading("IV. 리스크 평가 요약", level=1)

    table = doc.add_table(rows=6, cols=3)
    table.style = "Light Grid Accent 1"
    headers = ["리스크 영역", "위험 수준", "핵심 쟁점"]
    for i, header in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = header
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True

    risks = [
        ("Art. 28 위반 (프로세서 권한 초과)", "높음", "간주 컨트롤러 전환, 계약 위반, 고객 이탈"),
        ("Art. 5(1)(b) 목적 제한 원칙", "높음", "동의 없이는 AI 학습이 원래 목적과 양립 불가"),
        ("Art. 6(1)(f) 정당한 이익 (구조 변경 시)", "중-높음", "합리적 기대에서 균형 테스트 실패"),
        ("DPA 집행 조치", "중간", "AI 학습에 대한 적극적 집행 추세 (OpenAI, Clearview)"),
        ("계약/평판 리스크", "높음", "기업 고객 DPA 위반, 신뢰 훼손"),
    ]
    for row_idx, (area, level, issue) in enumerate(risks, 1):
        table.rows[row_idx].cells[0].text = area
        table.rows[row_idx].cells[1].text = level
        table.rows[row_idx].cells[2].text = issue

    doc.add_page_break()

    # === V. RECOMMENDATIONS ===
    doc.add_heading("V. 권고사항", level=1)

    doc.add_heading("방안 A: 고객 승인 AI 학습 (권장)", level=2)
    option_a = [
        "고객과의 DPA를 개정하여 가명처리/집계된 조달 데이터의 AI 모델 학습 사용을 명시적으로 승인받습니다.",
        "AI 학습을 기존 서비스 내 기능(지출 분석 부가가치)으로 포지셔닝하여, 고객이 서비스 관계의 일부로 승인하도록 합니다.",
        "고객이 (익명화/가명처리된) 데이터를 AI 학습 풀에 기여하는 것에 적극적으로 동의하는 명확한 옵트인 메커니즘을 구현합니다.",
        "어떤 데이터가 사용되는지, 모델이 어떻게 작동하는지, 어떤 안전조치가 적용되는지에 대한 투명성을 고객에게 제공합니다.",
        "고객이 자체 개인정보처리방침을 업데이트하여 정보주체에게 AI 관련 처리에 대해 고지하도록 보장합니다.",
    ]
    for item in option_a:
        doc.add_paragraph(item, style="List Number")

    doc.add_heading("방안 B: 익명화 우선 접근법", level=2)
    option_b = [
        "AI 학습 전에 강력한 익명화 또는 가명처리를 구현합니다.",
        "학습 데이터에서 모든 개인 식별자(성명, 이메일, 직책, 전화번호)를 제거하고, 상업적/거래 패턴만 유지합니다.",
        "데이터가 진정으로 익명화되면(EDPB 의견 28/2024의 높은 기준에 따라), GDPR이 학습 프로세스에 적용되지 않습니다.",
        "익명화 프로세스를 철저히 문서화합니다 — EDPB는 추출 및 쿼리 기반 식별 위험이 \"미미\"하다는 증거를 요구합니다.",
    ]
    for item in option_b:
        doc.add_paragraph(item, style="List Number")

    doc.add_heading("기술적 안전조치 (모든 방안에 공통 적용)", level=2)
    safeguards = [
        "모델 학습 중 차분 프라이버시(differential privacy) 기법 적용.",
        "데이터 최소화: 학습 전 개인 식별자를 제거하고 상업적 데이터 패턴만 사용.",
        "고객 데이터 분리: 모델 출력이 교차 고객 정보를 누출할 수 없도록 보장.",
        "추출 공격(멤버십 추론, 모델 역전, 재생성)에 대한 정기적 테스트.",
        "무조건적 처리 거부권 메커니즘 (디지털 옴니버스 제안에서 권장).",
        "Art. 35에 따른 데이터 보호 영향 평가(DPIA) — 이 규모의 AI 모델 학습은 의무적 영향 평가를 발동시킬 가능성이 높음.",
    ]
    for item in safeguards:
        doc.add_paragraph(item, style="List Bullet")

    doc.add_page_break()

    # === VI. CONCLUSION ===
    doc.add_heading("VI. 결론", level=1)

    doc.add_paragraph(
        "귀사는 현행 GDPR 체계 하에서, 데이터 처리자로서 자체 목적의 AI 모델을 고객 조달 데이터로 "
        "학습시키기 위해 정당한 이익(Art. 6(1)(f))에 단순히 의존할 수 없습니다. 근본적인 장애물은 "
        "Art. 28의 컨트롤러/프로세서 체계입니다: 자체 처리 목적을 결정하는 프로세서는 컨트롤러가 "
        "되며, 이에 따른 모든 법적 노출이 수반됩니다."
    )

    doc.add_paragraph(
        "컨트롤러 지위 문제가 고객 승인을 통해 해결되더라도, 정당한 이익 분석은 2단계(필요성)와 "
        "3단계(균형)에서 상당한 도전에 직면합니다. 주요 원인: (a) 덜 침해적인 대안(익명화/가명처리)의 "
        "존재; (b) AI 학습에 업무용 연락처가 사용되는 것에 대한 정보주체의 낮은 합리적 기대; "
        "(c) 교차 고객 데이터 집계 위험."
    )

    doc.add_paragraph(
        "디지털 옴니버스 제안(COM(2025) 837)이 채택되면 AI 개발을 정당한 이익으로 명시적으로 "
        "인정하는 더 유리한 체계를 제공할 것이나, 균형 테스트의 필요성을 제거하지는 않으며, "
        "프로세서/컨트롤러 선행 문제도 다루지 않습니다."
    )

    p = doc.add_paragraph()
    run = p.add_run("방안 A(고객 승인 AI 학습)를 ")
    run.bold = True
    p.add_run(
        "강력한 익명화/가명처리 조치와 결합하여 추진할 것을 권고합니다. 이 접근법은 "
        "프로세서 관계를 존중하고, 고객 투명성을 보장하며, GDPR 준수를 입증하는 가장 "
        "강한 법적 방어 기반을 제공합니다."
    )

    doc.add_paragraph("")

    # === DISCLAIMER ===
    doc.add_heading("면책 조항", level=1)

    disclaimer = doc.add_paragraph(
        "본 법률 분석 메모는 정보 제공 목적으로만 작성되었으며 법률 자문을 구성하지 않습니다. "
        "분석은 유럽연합 일반개인정보보호규정(EU 2016/679), 본 메모 작성일 기준의 EDPB "
        "가이던스, 및 아직 채택되지 않은 디지털 옴니버스 제안(COM(2025) 837)에 기반합니다. "
        "AI 및 개인정보보호에 대한 법적 환경은 빠르게 변화하고 있습니다. 귀사의 구체적인 "
        "준수 의무에 관한 사항은 관련 EU 관할권의 자격 있는 법률 자문을 받으시기 바랍니다."
    )
    disclaimer.style = "Quote"

    # === SOURCES ===
    doc.add_heading("인용 출처", level=1)
    sources = [
        "[Grade A] GDPR — 제5조, 제6조, 제28조, 제29조; 리시탈 47, 50",
        "[Grade A] EDPB 의견 28/2024 — AI 모델 맥락에서의 개인정보 처리 (2024.12.17 채택)",
        "[Grade A] EDPB 가이드라인 1/2024 — Art. 6(1)(f) 기반 개인정보 처리 (2024.10.08 채택)",
        "[Grade A] CJEU 사건 C-252/21, Meta v. Bundeskartellamt (2023.07.04)",
        "[Grade A] CJEU 사건 C-26/22, SCHUFA Holding (2023.12.07)",
        "[Grade B] COM(2025) 837 final — 디지털 입법 옴니버스 (2025.11.19 제안)",
        "[Grade B] Garante v OpenAI (ChatGPT) — 1,500만 유로 (2024.12.20)",
        "[Grade B] AP Netherlands v Clearview AI — 3,050만 유로 (2024.05.16)",
    ]
    for s in sources:
        doc.add_paragraph(s, style="List Bullet")

    path = OUTPUT_DIR / "Legal_Opinion_AI_Training_GDPR_KR.docx"
    doc.save(str(path))
    print(f"Korean opinion saved: {path}")
    return path


if __name__ == "__main__":
    en_path = generate_english_opinion()
    kr_path = generate_korean_opinion()
    print(f"\nBoth documents generated successfully:")
    print(f"  English: {en_path}")
    print(f"  Korean:  {kr_path}")
