#!/usr/bin/env python3
"""Generate DOCX legal analysis memos from markdown source files."""

import re
import os
from pathlib import Path
from docx import Document
from docx.shared import Pt, Inches, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

DEFAULT_OUTPUT_DIR = Path.home() / "Legal-private" / "gdpr-expert" / "opinions"


def get_output_dir() -> Path:
    raw = os.environ.get("GDPR_EXPERT_PRIVATE_DIR", "").strip()
    output_dir = Path(raw).expanduser() if raw else DEFAULT_OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


OUTPUT_DIR = get_output_dir()


def set_cell_shading(cell, color_hex):
    """Set background shading for a table cell."""
    shading = cell._element.get_or_add_tcPr()
    shading_elem = shading.makeelement(qn('w:shd'), {
        qn('w:val'): 'clear',
        qn('w:color'): 'auto',
        qn('w:fill'): color_hex
    })
    shading.append(shading_elem)


def style_document(doc):
    """Apply base styling to document."""
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)

    for section in doc.sections:
        section.top_margin = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin = Cm(2.54)
        section.right_margin = Cm(2.54)


def add_title_page(doc, title, subtitle, date, author, recipient, lang='en'):
    """Add a formatted title page."""
    for _ in range(4):
        doc.add_paragraph('')

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run('LEGAL ANALYSIS MEMO' if lang == 'en' else '\ubc95\ub960 \ubd84\uc11d \uba54\ubaa8')
    run.font.size = Pt(28)
    run.font.color.rgb = RGBColor(0x00, 0x2B, 0x5C)
    run.bold = True

    doc.add_paragraph('')

    # Horizontal line
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run('\u2500' * 60)
    run.font.color.rgb = RGBColor(0x00, 0x2B, 0x5C)

    doc.add_paragraph('')

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(title)
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

    doc.add_paragraph('')
    doc.add_paragraph('')

    # Metadata table
    meta = [
        ('Date' if lang == 'en' else '\uc77c\uc790', date),
        ('Generated by' if lang == 'en' else '\uc0dd\uc131 \uc8fc\uccb4', author),
        ('Request Context' if lang == 'en' else '\uc694\uccad \ub9e5\ub77d', recipient),
        ('Classification' if lang == 'en' else '\ubd84\ub958',
         'Confidential \u2014 Review Draft' if lang == 'en'
         else '\uae30\ubc00 \u2014 \uac80\ud1a0 \ucd08\uc548'),
    ]

    table = doc.add_table(rows=len(meta), cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, (label, value) in enumerate(meta):
        cell_label = table.cell(i, 0)
        cell_value = table.cell(i, 1)
        cell_label.width = Inches(1.8)
        cell_value.width = Inches(4.2)

        p_label = cell_label.paragraphs[0]
        p_label.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        run_label = p_label.add_run(label + ':')
        run_label.bold = True
        run_label.font.size = Pt(11)
        run_label.font.color.rgb = RGBColor(0x00, 0x2B, 0x5C)

        p_value = cell_value.paragraphs[0]
        run_value = p_value.add_run('  ' + value)
        run_value.font.size = Pt(11)

    doc.add_page_break()


def parse_md_to_docx(md_path, docx_path, lang='en'):
    """Parse markdown and create a styled DOCX document."""
    doc = Document()
    style_document(doc)

    with open(md_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    # Title page
    if lang == 'en':
        title = 'Lawfulness of Using Client Procurement Data to Fine-Tune an LLM\nfor AI-Powered Spend Analytics Under the GDPR'
        subtitle = 'Legitimate Interest (Art. 6(1)(f)) Analysis'
    else:
        title = 'GDPR\uc0c1 AI \uae30\ubc18 \uc9c0\ucd9c \ubd84\uc11d \uae30\ub2a5\uc744 \uc704\ud55c\n\uace0\uac1d \uc870\ub2ec \ub370\uc774\ud130\uc758 LLM \ubbf8\uc138\uc870\uc815 \uc801\ubc95\uc131 \uac80\ud1a0'
        subtitle = '\uc815\ub2f9\ud55c \uc774\uc775 (Art. 6(1)(f)) \ubd84\uc11d'

    add_title_page(
        doc,
        title=title,
        subtitle=subtitle,
        date='26 March 2026' if lang == 'en' else '2026\ub144 3\uc6d4 26\uc77c',
        author='Jinju Legal Orchestrator \u2014 Privacy Specialist Kim De Bruyne (\uae40\ub355\ubc30)',
        recipient='[Client] \u2014 B2B SaaS Procurement Platform',
        lang=lang
    )

    # Skip the first few metadata lines in MD
    i = 0
    skip_initial = True
    in_table = False
    table_rows = []

    while i < len(lines):
        line = lines[i].rstrip('\n')
        stripped = line.strip()

        # Skip initial title block (already on title page)
        if skip_initial:
            if (
                stripped.startswith('# LEGAL OPINION')
                or stripped.startswith('# LEGAL ANALYSIS MEMO')
                or stripped.startswith('# \ubc95\ub960 \uc758\uacac\uc11c')
                or stripped.startswith('# \ubc95\ub960 \ubd84\uc11d \uba54\ubaa8')
            ):
                i += 1
                continue
            if stripped.startswith('## Re:') or stripped.startswith('## \uac74:'):
                i += 1
                continue
            if stripped.startswith('**Date:') or stripped.startswith('**\uc77c\uc790:'):
                i += 1
                continue
            if (
                stripped.startswith('**Prepared')
                or stripped.startswith('**Generated')
                or stripped.startswith('**\uc791\uc131\uc790')
                or stripped.startswith('**\uc0dd\uc131 \uc8fc\uccb4')
            ):
                i += 1
                continue
            if (
                stripped.startswith('**For:')
                or stripped.startswith('**Request Context:')
                or stripped.startswith('**\uc218\uc2e0:')
                or stripped.startswith('**\uc694\uccad \ub9e5\ub77d:')
            ):
                i += 1
                continue
            if stripped.startswith('**Classification') or stripped.startswith('**\ubd84\ub958:'):
                i += 1
                continue
            if stripped == '---':
                skip_initial = False
                i += 1
                continue
            if stripped == '':
                i += 1
                continue
            skip_initial = False

        # Handle tables
        if stripped.startswith('|') and '|' in stripped[1:]:
            if not in_table:
                in_table = True
                table_rows = []
            # Skip separator rows
            if re.match(r'^\|[\s\-:|]+\|$', stripped):
                i += 1
                continue
            cells = [c.strip() for c in stripped.split('|')[1:-1]]
            table_rows.append(cells)
            i += 1
            continue
        elif in_table:
            # End of table, render it
            if table_rows:
                num_cols = max(len(r) for r in table_rows)
                tbl = doc.add_table(rows=len(table_rows), cols=num_cols)
                tbl.style = 'Table Grid'
                tbl.alignment = WD_TABLE_ALIGNMENT.CENTER

                for ri, row in enumerate(table_rows):
                    for ci, cell_text in enumerate(row):
                        if ci < num_cols:
                            cell = tbl.cell(ri, ci)
                            p = cell.paragraphs[0]
                            # Bold header row
                            if ri == 0:
                                run = p.add_run(cell_text)
                                run.bold = True
                                run.font.size = Pt(10)
                                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                                set_cell_shading(cell, '002B5C')
                            else:
                                run = p.add_run(cell_text)
                                run.font.size = Pt(10)
                                if ri % 2 == 0:
                                    set_cell_shading(cell, 'F0F4F8')

                doc.add_paragraph('')
            in_table = False
            table_rows = []
            # Don't increment i, process this line

        # Headings
        if stripped.startswith('## '):
            heading_text = stripped[3:].strip()
            p = doc.add_heading(heading_text, level=1)
            for run in p.runs:
                run.font.color.rgb = RGBColor(0x00, 0x2B, 0x5C)
            i += 1
            continue

        if stripped.startswith('### '):
            heading_text = stripped[4:].strip()
            p = doc.add_heading(heading_text, level=2)
            for run in p.runs:
                run.font.color.rgb = RGBColor(0x00, 0x4D, 0x8C)
            i += 1
            continue

        if stripped.startswith('#### '):
            heading_text = stripped[5:].strip()
            p = doc.add_heading(heading_text, level=3)
            i += 1
            continue

        if stripped.startswith('##### '):
            heading_text = stripped[6:].strip()
            p = doc.add_heading(heading_text, level=4)
            i += 1
            continue

        # Horizontal rules → page breaks for major sections
        if stripped == '---':
            i += 1
            continue

        # Block quotes
        if stripped.startswith('> '):
            quote_lines = []
            while i < len(lines) and lines[i].strip().startswith('>'):
                quote_text = lines[i].strip().lstrip('> ').strip()
                if quote_text:
                    quote_lines.append(quote_text)
                i += 1

            full_quote = ' '.join(quote_lines)
            # Clean markdown formatting from quotes
            full_quote = re.sub(r'\*\*(.+?)\*\*', r'\1', full_quote)

            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Cm(1.5)
            p.paragraph_format.right_indent = Cm(1.0)
            run = p.add_run(full_quote)
            run.italic = True
            run.font.size = Pt(10.5)
            run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
            continue

        # Empty lines
        if stripped == '':
            i += 1
            continue

        # Regular paragraphs with inline formatting
        p = doc.add_paragraph()
        add_formatted_text(p, stripped)

        i += 1

    # Handle any remaining table
    if in_table and table_rows:
        num_cols = max(len(r) for r in table_rows)
        tbl = doc.add_table(rows=len(table_rows), cols=num_cols)
        tbl.style = 'Table Grid'
        for ri, row in enumerate(table_rows):
            for ci, cell_text in enumerate(row):
                if ci < num_cols:
                    cell = tbl.cell(ri, ci)
                    p = cell.paragraphs[0]
                    if ri == 0:
                        run = p.add_run(cell_text)
                        run.bold = True
                        run.font.size = Pt(10)
                    else:
                        run = p.add_run(cell_text)
                        run.font.size = Pt(10)

    doc.save(str(docx_path))
    print(f'Generated: {docx_path}')


def add_formatted_text(paragraph, text):
    """Add text with basic inline formatting (bold, italic)."""
    # Process inline markdown: **bold**, *italic*, [VERIFIED] tags
    parts = re.split(r'(\*\*.*?\*\*|\*.*?\*|\[VERIFIED\]|\[Grade [A-D]\]|\[UNVERIFIED\]|\[WEB\])', text)

    for part in parts:
        if not part:
            continue
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
            run.font.size = Pt(11)
        elif part.startswith('*') and part.endswith('*') and not part.startswith('**'):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
            run.font.size = Pt(11)
        elif part == '[VERIFIED]':
            run = paragraph.add_run('[VERIFIED]')
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x00, 0x80, 0x00)
            run.bold = True
        elif part.startswith('[Grade'):
            run = paragraph.add_run(part)
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x00, 0x4D, 0x8C)
            run.bold = True
        elif part == '[UNVERIFIED]':
            run = paragraph.add_run('[UNVERIFIED]')
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0xFF, 0x8C, 0x00)
            run.bold = True
        else:
            run = paragraph.add_run(part)
            run.font.size = Pt(11)


if __name__ == '__main__':
    en_md = OUTPUT_DIR / '2026-03-26-ai-model-training-legitimate-interest-EN.md'
    ko_md = OUTPUT_DIR / '2026-03-26-ai-model-training-legitimate-interest-KO.md'
    en_docx = OUTPUT_DIR / '2026-03-26-ai-model-training-legitimate-interest-EN.docx'
    ko_docx = OUTPUT_DIR / '2026-03-26-ai-model-training-legitimate-interest-KO.docx'

    parse_md_to_docx(en_md, en_docx, lang='en')
    parse_md_to_docx(ko_md, ko_docx, lang='ko')
    print('Done.')
